name: proyecto
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #Logo
    - images/f1logo2.jpg
    - images/portada.png
    #Pilotos y Numeros
    - images/Pilotos/Pequeños/hamilton.png
    - images/Pilotos/Numeros/44.png
    - images/Pilotos/Pequeños/bottas.png
    - images/Pilotos/Numeros/77.png
    - images/Pilotos/Pequeños/vettel.png
    - images/Pilotos/Numeros/5.png
    - images/Pilotos/Pequeños/leclerc.png
    - images/Pilotos/Numeros/16.png
    - images/Pilotos/Pequeños/verstappen.png
    - images/Pilotos/Numeros/33.png
    - images/Pilotos/Pequeños/albon.png
    - images/Pilotos/Numeros/23.png
    - images/Pilotos/Pequeños/sainz.png
    - images/Pilotos/Numeros/55.png
    - images/Pilotos/Pequeños/norris.png
    - images/Pilotos/Numeros/4.png
    - images/Pilotos/Pequeños/ricciardo.png
    - images/Pilotos/Numeros/3.png
    - images/Pilotos/Pequeños/ocon.png
    - images/Pilotos/Numeros/31.png
    - images/Pilotos/Pequeños/gasly.png
    - images/Pilotos/Numeros/10.png
    - images/Pilotos/Pequeños/kvyat.png
    - images/Pilotos/Numeros/26.png
    - images/Pilotos/Pequeños/perez.png
    - images/Pilotos/Numeros/11.png
    - images/Pilotos/Pequeños/stroll.png
    - images/Pilotos/Numeros/18.png
    - images/Pilotos/Pequeños/raikkonen.png
    - images/Pilotos/Numeros/7.png
    - images/Pilotos/Pequeños/giovinazzi.png
    - images/Pilotos/Numeros/99.png
    - images/Pilotos/Pequeños/magnussen.png
    - images/Pilotos/Numeros/20.png
    - images/Pilotos/Pequeños/grosjean.png
    - images/Pilotos/Numeros/8.png
    - images/Pilotos/Pequeños/russell.png
    - images/Pilotos/Numeros/63.png
    - images/Pilotos/Pequeños/latifi.png
    - images/Pilotos/Numeros/6.png
    #Logo Equipos
    - images/LogoEquipos/logomercedes.png
    - images/LogoEquipos/logoferrari.png
    - images/LogoEquipos/logoredbull.png
    - images/LogoEquipos/logomclaren.png
    - images/LogoEquipos/logorenault.png
    - images/LogoEquipos/logoalphatauri.png
    - images/LogoEquipos/logoracingpoint.png
    - images/LogoEquipos/logoalfaromeo.png
    - images/LogoEquipos/logohaas.png
    - images/LogoEquipos/logowilliams.png
    #Imagen Coche
    - images/Equipos/mercedes.png
    - images/Equipos/ferrari.png
    - images/Equipos/redbull.png
    - images/Equipos/mclaren.png
    - images/Equipos/renault.png
    - images/Equipos/alphatauri.png
    - images/Equipos/racingpoint.png
    - images/Equipos/alfaromeo.png
    - images/Equipos/haas.png
    - images/Equipos/williams.png
    
    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
